let nome = prompt("Inserisci il nome");
let cognome = prompt("Inserisci il cognome");
let colorepref = prompt("Inserisci colore preferita");
let num1 = prompt("Inserisci numero per devidere");
let num2 = prompt("Inserisci numero che devide");
let dev = parseInt(num1)/parseInt(num2);
let pwrd;
console.log(nome+cognome+colorepref+dev);
pwrd = nome+cognome+colorepref+dev;
document.getElementById("p-nome").innerHTML = "Nome: " + nome;
document.getElementById("p-cognome").innerHTML = "Cognome: " + cognome;
document.getElementById("p-color").innerHTML = "Colore preferita: " + colorepref;
document.getElementById("pwd").innerHTML= "Password: "+ pwrd;